/**
 * RP.Dash.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1-prerelease
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient'
import Goal from './models/Goal'
import GoalStats from './models/GoalStats'
import DataResponse from './models/DataResponse'
import User from './models/User'
import UserClient from './models/UserClient'
import UserProject from './models/UserProject'
import UserTag from './models/UserTag'
import UserWorkspace from './models/UserWorkspace'
import AuthApi from './api/AuthApi'
import DailyGoalApi from './api/DailyGoalApi'
import DemoApi from './api/DemoApi'
import StatsApi from './api/StatsApi'
import TogglAccountApi from './api/TogglAccountApi'
import UsersApi from './api/UsersApi'

/**
 * ERROR_UNKNOWN.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var RelativelyProductive = require('RelativelyProductive/index'); // See note below*.
 * var xxxSvc = new RelativelyProductive.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new RelativelyProductive.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['RelativelyProductive/index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new RelativelyProductive.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new RelativelyProductive.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module RelativelyProductive/index
 * @version v1-prerelease
 */
export {
  /**
   * The ApiClient constructor.
   * @property {module:RelativelyProductive/ApiClient}
   */
  ApiClient,
  /**
   * The DataResponse model constructor.
   * @property {module:RelativelyProductive/models/DataResponse}
   */
  DataResponse,
  /**
   * The Goal model constructor.
   * @property {module:RelativelyProductive/models/Goal}
   */
  Goal,
  /**
   * The GoalStats model constructor.
   * @property {module:RelativelyProductive/models/GoalStats}
   */
  GoalStats,
  /**
   * The User model constructor.
   * @property {module:RelativelyProductive/models/User}
   */
  User,
  /**
   * The UserClient model constructor.
   * @property {module:RelativelyProductive/models/UserClient}
   */
  UserClient,
  /**
   * The UserProject model constructor.
   * @property {module:RelativelyProductive/models/UserProject}
   */
  UserProject,
  /**
   * The UserTag model constructor.
   * @property {module:RelativelyProductive/models/UserTag}
   */
  UserTag,
  /**
   * The UserWorkspace model constructor.
   * @property {module:RelativelyProductive/models/UserWorkspace}
   */
  UserWorkspace,
  /**
   * The AuthApi service constructor.
   * @property {module:RelativelyProductive/api/AuthApi}
   */
  AuthApi,
  /**
   * The DailyGoalApi service constructor.
   * @property {module:RelativelyProductive/api/DailyGoalApi}
   */
  DailyGoalApi,
  /**
   * The DemoApi service constructor.
   * @property {module:RelativelyProductive/api/DemoApi}
   */
  DemoApi,
  /**
   * The StatsApi service constructor.
   * @property {module:RelativelyProductive/api/StatsApi}
   */
  StatsApi,
  /**
   * The TogglAccountApi service constructor.
   * @property {module:RelativelyProductive/api/TogglAccountApi}
   */
  TogglAccountApi,
  /**
   * The UsersApi service constructor.
   * @property {module:RelativelyProductive/api/UsersApi}
   */
  UsersApi,
}
